campfire:
  common: # settings for the common campfire
    max-burning-time-millis: 60000 # time = item, that is max items which can contain in campfire, and in same case, igniting time of campfire
    burning-items: # items which player can place to campfire and ignite times of items. You can receive all items list from this link: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html#enum-constant-summary
      STICK: 5000
      COAL: 15000
      OAK_PLANKS: 30000
    explosive-reaction: # in this section you can customize explosive reaction, in this case, explosive reaction is reaction on gunpowder and TNT
      enable: true # disable or enable this functional
      damage-of-gunpowder: 2.0 # damage when the player interact to the igniting campfire with the gunpowder in the arm
      power-of-TNT: 4.0 # power of explosion when player interact to the igniting campfire with the TNT in the arm. The value 4.0 is equal then common TNT explode in Minecraft
      set-fire-after-explode: true # additional setting: ignite blocks or not when are in explosion radius
      break-blocks-after-explode: true # additional setting: break blocks or not when are in explosion radius

  soul: # settings for soul campfire
    max-burning-time-millis: 120000 # time = item, that is max items which can contain in campfire, and in same case, igniting time of campfire
    burning-items: # items which player can place to campfire and ignite times of items. You can receive all items list from this link: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html#enum-constant-summary
      STICK: 5000
      COAL: 15000
      OAK_PLANKS: 30000
    explosive-reaction: # in this section you can customize explosive reaction, in this case, explosive reaction is reaction on gunpowder and TNT
      enable: true # disable or enable this functional
      damage-of-gunpowder: 2.0 # damage when the player interact to the igniting campfire with the gunpowder in the arm
      power-of-TNT: 4.0 # power of explosion when player interact to the igniting campfire with the TNT in the arm. The value 4.0 is equal then common TNT explode in Minecraft
      set-fire-after-explode: true # additional setting: ignite blocks or not when are in explosion radius
      break-blocks-after-explode: true # additional setting: break blocks or not when are in explosion radius

  # Settings for allow or disallow igniting by different types torch.
  # When a player use a torch for the igniting campfire, the torch can add time to igniting if STICK item contains in the burning-items list.
  # If a campfire is not igniting, the torch can ignite the campfire and add the time of igniting.
  allow-fire-campfire-by-torch:
    torch: true
    soul-torch: true
    redstone-torch: true

  progress-bar: # settings for configure progress bar view
    size: 10 # size of indicate cells
    draw-distance: 10 # draw distance that apply when the player always can see the campfire indicator
    draw-distance-personally: 3 # draw distance that apply when the player hover on the campfire

    # When a player in CREATIVE or SPECTATOR mode, the player can see a progress bar with the distance in draw-distance parameter.
    # When a player in SURVIVAL or ADVENTURE mode, the player can see a progress bar only then the player hover on a campfire...
    # ... BUT if draw-for-survival value is true, then the player can see the progress bar with same logic of first variant.
    draw-for-survival: false

    draw-Y-offset: -0.20 # Y progress bar offset of campfire. The progress bar starts with the same height that nickname of the player.

    symbol: # the symbols that uses for build a progress bar. One symbol = one cell, then size parameter sets size to line of these symbols.
      back: "&c░" # this symbol will be used if the cell is empty
      front: "&a█" # this symbol will be used for fill if the cell is not empty

  database-filename: "database.db" # the database file name. Local database will be used for save campfires state after the server stop.