name: RealisticCampfires
version: '${version}'
main: team.rubyhorizon.campfires.RealisticCampfiresPlugin
api-version: '1.19'
authors:
  - Ruby Horizon Team
  - Salatisik
  - Shershnyaga_
load: POSTWORLD
depend: [ProtocolLib]
libraries:
  - org.xerial:sqlite-jdbc:3.46.0.0